### ISSUE TITLE
GammaOS overwritten boot

### ISSUE THREAD

**Issue by abDroiX** [TheGammaSqueeze/GammaOS-RK3566#1]
1. installed GammaOS as stated by instructions on ARC-D -> https://github.com/TheGammaSqueeze/GammaOS-RK3566#help-my-device-is-no-longer-booting-or-i-want-to-go-back-to-stock-os
2. downloaded Android & Linux firmware as instructed by Anbernic -> https://win.anbernic.com/download/289.html
3. when trying to install an image file onto ARC-D, it simply ignores the SD Card and boots into GammaOS, where it proceeds to just shut off.

https://droidbox-my.sharepoint.com/:v:/g/personal/aaron_b_droix_co_uk/EdwbncEv5bJLhdui5JHCxE8B1iOJrUFv0Xe46haouewVUw?e=R5n8Gl

Large logo:
![PXL_20231205_155758534](https://github.com/TheGammaSqueeze/GammaOS-RK3566/assets/153003475/30e73510-4e4e-4522-ab86-6ccc6e253cac)

Then smaller logo:
![PXL_20231205_155808780](https://github.com/TheGammaSqueeze/GammaOS-RK3566/assets/153003475/01d02fc8-0fa6-4ba0-ab8b-41a8da14b3bc)

Device is starting message right before turning off:
![PXL_20231205_160008578](https://github.com/TheGammaSqueeze/GammaOS-RK3566/assets/153003475/37ffe77d-904a-407c-bdca-a3d5142eb841)

**Comment by TheGammaSqueeze** [comment]
Can you try a factory reset?
Hold down volume down as you power the device on.
Choose factory reset.

When booting Android with a Linux SD card inserted, do not hold down F to boot into Android. Instead eject the sd card.

**Comment by TheGammaSqueeze** [comment]
Also do not set a password on the  lock screen.

**Comment by TheGammaSqueeze** [comment]
This has been fixed on the GammaOS 1.5.1 release.
