### ISSUE TITLE
RG353P - Audio Jack

### ISSUE THREAD

**Issue by Zopenko** [TheGammaSqueeze/GammaOS-RK3566#2]
Installed the GammaOS light version on the RG353P, when headphones are connected to the Audio Jack, sound comes out from both the unit speakers AND the wired headphones. 
This does not happen on the Linux side. Sound only comes from the wired headphones AND speakers are silent.

**Comment by jd6-37** [comment]
Same here on the ARC-D.

**Comment by jcursiolf** [comment]
I also have this issue. My "fix" while waiting for a real fix is using a USB-C to AUX dongle (like for most top smartphones nowadays) on the OTG USB-C port.

**Comment by danthemen64** [comment]
I have a similar issue on RG353V (full install with Google play services/store). Audio continues to play on the external speaker when wired headphones are connected to the audio jack. No audio plays through the headphones. Speaker/headphones audio worked as expected on the stock Android OS, headphone audio only failed after installing Gamma.

**Comment by TheGammaSqueeze** [comment]
Fixed on GammaOS 1.5.1.

**Comment by danthemen64** [comment]
> Fixed on GammaOS 1.5.1.

Working great on RG353V! Thank you!

**Comment by Zopenko** [comment]
> Fixed on GammaOS 1.5.1.

Thank you, working great on RG353P
